version: '3.3'

services:

  frontend-dev:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - hydrovault

networks:
  hydrovault:
    # use the bridge driver, but enable IPv6
    driver: bridge